name: FartPush

on:
  push:
    branches: [ master ]
  schedule:
    - cron: 0 0,14 * * *
  workflow_dispatch:
  

jobs:
  FastPush:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Requirements
        run: |
          sudo pip3 install -r requirements.txt

      - name: Push On
        run: |
          dingtoken='${{ secrets.DINGTOKEN }}'
          dingsecret='${{ secrets.DINGSECRET }}'
          python3 push.py --dingtoken ${dingtoken} --dingsecret ${dingsecret}
